# .github/workflows/chromatic.yml

# name of our action
name: "Chromatic"
# the event that will trigger the action
on:
  push:
    branches-ignore:
      - "renovate/**"
      - "main"

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - run: yarn --pure-lockfile
      #- run: yarn build-storybook
      - uses: chromaui/action@v1
        # options required to the GitHub chromatic action
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: storybook:build
