## name of our action
name: Test

# the event that will trigger the action
on: pull_request

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn --pure-lockfile

      - name: Test Build
        run: yarn build

      - name: Test Coverage
        run: yarn test:coverage

      - name: Test Storybook
        run: yarn storybook:build:docs
